# Generated by Django 2.1.14 on 2020-01-19 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 19, 8, 47, 3, 815054, tzinfo=utc))),
                ('details', models.CharField(max_length=255)),
                ('isVerified', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
